server:
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: api-gateway_logs
    static_configs:
      - targets: [localhost]
        labels:
          env: dev
          project: wms
          __path__: /data/logs/api-gateway/*.log
    
    pipeline_stages:
      - multiline:
          firstline: ^\d{4}-\d{2}-\d{2}
      
      - regex:
          source: filename
          expression: ".*/(?P<instance_name>.*)/.*\\.log"
      
      - regex:
          expression: "^\\S+ +(?P<level_name>\\S+) .*"
          
      - labels:
          job: instance_name
          level: level_name

  - job_name: api-gateway_logs
    static_configs:
      - targets: [localhost]
        labels:
          env: dev
          project: wms
          __path__: /data/logs/auth-service/*.log
    
    pipeline_stages:
      - multiline:
          firstline: ^\d{4}-\d{2}-\d{2}
      
      - regex:
          source: filename
          expression: ".*/(?P<instance_name>.*)/.*\\.log"
      
      - regex:
          expression: "^\\S+ +(?P<level_name>\\S+) .*"
          
      - labels:
          job: instance_name
          level: level_name