server:
  port: 8001
  netty:
    connection-timeout: 2s
    idle-timeout: 30s



spring:
  application:
    name: product-service
# ================================ message queue ===============================

# ================================ oauth2 ===============================
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.icuture.icu/realms/cloud/protocol/openid-connect/certs  
# ================================ oauth2 ===============================

# ================================database ===============================
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://ep-restless-cell-a19w8zl1-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_DbZ28PeUsdHW
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://ep-restless-cell-a19w8zl1-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    user: neondb_owner
    password: npg_DbZ28PeUsdHW
    locations: classpath:db/migration           
    baseline-on-migrate: true                    
    clean-disabled: false
# ================================database ===============================

# ================================logging ===============================
logging:
  level:
    root: INFO
    brave: DEBUG
    reactor.netty: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO
    org.springframework.cloud: INFO
    com.cloud.product-service: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/product-service.log
    max-size: 10MB
    max-history: 7

# ================================management ===============================

# ================================tracing & health ===============================
management:
  health:
    show-details: always
    show-components: always
    diskspace:
      enabled: true
    refresh:
      enabled: true
    probes:
      enabled: true
    
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,threaddump,heapdump,prometheus,zipkin
      base-path: /actuator
    
  mappings:
    health: healthcheck

  tracing:
    sampling:
      probability: 1.0
  
  # zipkin:
  #   tracing:
  #     endpoint: http://zipkin:9411/api/v2/spans
  #     connect-timeout: 1s
  #     read-timeout: 5s
    
# ================================tracing & health ===============================
