server:
  port: 8003
  netty:
    connection-timeout: 2s
    idle-timeout: 30s
    
spring:
  application:
    name: inventory-service
  kafka:
    bootstrap-servers: kafka-apache:9092

    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        # Tăng timeout để tránh fail khi Kafka khởi động chậm
        session.timeout.ms: 45000
        request.timeout.ms: 60000
        connection.timeout.ms: 60000   # quan trọng

        # Cấu hình JsonDeserializer đúng cách (Spring Boot 3.x)
        spring.json.trusted.packages: "*"

        # Type mapping (nếu cần nhiều class)
        spring.json.type.mapping: >-
          com.cloud.order_service.application.dto.event.OrderApprovedEvent:com.cloud.inventory.application.kafka.event.OrderApprovedEvent,
          com.cloud.order_service.application.dto.event.OrderCancelledEvent:com.cloud.inventory.application.kafka.event.OrderCancelledEvent,
          com.cloud.order_service.application.dto.event.OrderShippedEvent:com.cloud.inventory.application.kafka.event.OrderShippedEvent,
          com.cloud.order_service.application.dto.event.InboundCompletedEvent:com.cloud.inventory.application.kafka.event.OrderInboundRequest



    listener:
      auto-startup: true
      missing-topics-fatal: false
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 3
# ================================ oauth2 ===============================
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.icuture.icu/realms/cloud/protocol/openid-connect/certs  
# ================================ oauth2 ===============================

# ================================database ===============================
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://ep-snowy-wildflower-a11x7r90-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_KnGvRYJ70lHm
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://ep-snowy-wildflower-a11x7r90-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    user: neondb_owner
    password: npg_KnGvRYJ70lHm
    locations: classpath:db/migration           
    baseline-on-migrate: true                    
    # schemas: user_service
    clean-disabled: false
# ================================database ===============================

# ================================logging ===============================
logging:
  level:
    root: INFO
    brave: DEBUG
    reactor.netty: INFO
    org.springframework.kafka: DEBUG
    org.springframework.web: INFO
    org.springframework.cloud: DEBUG
    com.cloud.inventory-service: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/inventory-service.log
    max-size: 10MB
    max-history: 7

# ================================management ===============================

# ================================tracing & health ===============================
management:
  health:
    show-details: always
    show-components: always
    diskspace:
      enabled: true
    refresh:
      enabled: true
    probes:
      enabled: true
    
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,threaddump,heapdump,prometheus,zipkin
      base-path: /actuator
    
  mappings:
    health: healthcheck

  tracing:
    sampling:
      probability: 1.0
  
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
      connect-timeout: 1s
      read-timeout: 5s
    
# ================================tracing & health ===============================
